### ISSUE TITLE
Image for v4.0.0

### ISSUE THREAD

**Issue by iromli** [GluuFederation/docker-oxPassport#2]
Develop `gluufederation/oxpassport:4.0.0` image.

**Comment by iromli** [comment]
On container startup, the following errors are thrown:

```
2019-05-07T18:03:22.864Z [WARN]     An attempt to get configuration data will be tried again soon
2019-05-07T18:04:22.925Z [ERROR]    Error: Received unexpected HTTP status code of 503
2019-05-07T18:04:22.925Z [ERROR]    Error: Received unexpected HTTP status code of 503
    at reqp.then.response (/opt/gluu/node/passport/server/utils/configDiscovery.js:39:13)
    at tryCatcher (/opt/gluu/node/passport/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/gluu/node/passport/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/gluu/node/passport/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/gluu/node/passport/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/gluu/node/passport/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/opt/gluu/node/passport/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/opt/gluu/node/passport/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/opt/gluu/node/passport/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/gluu/node/passport/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
```

**Comment by iromli** [comment]
The image has been pushed.
